name: Static Website Check

on:
  push:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

      - name: Check index.html exists
        run: test -f index.html